### ISSUE TITLE
Can't global install pa11y

### ISSUE THREAD

**Issue by RobinKnipe** [pa11y/pa11y#532] opened 2020-10-22 09:05 UTC
## Expected behaviour
```shell
npm i -g pa11y
```
Should globally install the tool for use anywhere (as indicated in the docs).

## Actual behaviour
The install begins but hits a problem adding `chromium`:
```npm
$ npm i -g pa11y
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robin/.npm/_logs/2020-10-22T08_47_56_309Z-debug.log
```
I've tried this - and hit the exact same problem - running with `sudo`, and as the `root` user.
Perhaps more frustratingly, I would expect the installation not to have to perform this step as I already have `chromium` installed on my device.

## Steps to reproduce
Run the installation instruction from the README: `npm i -g pa11y`

## Environment:
```npx
npx pa11y --environment
Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
Pa11y:      5.3.0
Node.js:    14.13.1
npm:        6.14.8
OS:         5.4.0-48-generic (linux)
```

**Comment by josebolos** [comment] 2020-10-22 09:41
Hi @RobinKnipe 

Thanks for creating this issue.

As the error message says, this will happen if your user doesn't have write permissions in that particular folder.

Could you please list the permissions of the /usr/local/lib/node_modules folder and verify that your user has writing permission?

```sh
ls -al /usr/local/lib/node_modules
```

Thanks!

**Comment by RobinKnipe** [comment] 2020-10-22 10:00
Hi @josebolos  :wave: - please forgive my freshness to this project... If I run `sudo npm i -g pa11y`, the process should have everything it needs to successfully complete the installation? For example I would expect the following command to succeed, no matter what the permissions of `/usr/local/lib/node_modules` are:
```
$ sudo npm i -g pa11y
/usr/local/bin/pa11y -> /usr/local/lib/node_modules/pa11y/bin/pa11y.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/pa11y/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robin/.npm/_logs/2020-10-22T08_48_15_607Z-debug.log
```

**Comment by RobinKnipe** [comment] 2020-10-22 10:11
P.S.
I also note that sadly `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true sudo npm i -g pa11y` doesn't help, although that looks more like a `pupeteer` failure :disappointed:

**Comment by MCDELTAT** [comment] 2020-11-16 19:07
@RobinKnipe What Linux Distro are you using and how did you install it.? Just tried to replicate this using Linux Mint 20 and Node 14.15.1 (via NVM) and everything worked fine.

```
aaron@aaron-Mint-Rig:~$ npx pa11y --environment
Pa11y:      5.3.0
Node.js:    14.15.1
npm:        6.14.8
OS:         5.4.0-52-generic (linux)
```

It should be noted that with my install of node via NVM, that it doesn't even use the `/usr/local/lib/node_modules` folder, but instead ` /home/aaron/.nvm/versions/node/v14.15.1/lib/node_modules/`

I can try to replicate, but it likely is just permissions on your machine and not an issue with the project.

**Comment by RobinKnipe** [comment] 2020-11-18 08:44
Hi @MCDELTAT - I'm on Kubuntu18.04 (probably time for an upgrade!). While there might be some advantages to moving my main `node_modules` cache into my home directory, there will certainly be consequences of this, and it really doesn't feel like something that should be necessary, especially as I have super-user/root access to my machine.

**Comment by EvgeniiaVak** [comment] 2020-11-22 07:18
Same issue here (same exact [stack trace](https://github.com/pa11y/pa11y/issues/532#issuecomment-714380471)). `sudo` doesn't help. I'm running linux in windows (WSL2):

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
```

And it does seem like an issue with puppeteer, because trying to install it results in the same error: 
```
$ sudo npm install -g puppeteer
> puppeteer@5.5.0 install /usr/local/lib/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r818858! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@5.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@5.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-22T07_08_58_913Z-debug.log
```

Here is the related issue - https://github.com/puppeteer/puppeteer/issues/375

and the [command adapted from the same issue](https://github.com/puppeteer/puppeteer/issues/375#issuecomment-363466257) worked 🎉  - pa11y installed successfully:
```
$ sudo npm install -g pa11y --unsafe-perm=true
/usr/local/bin/pa11y -> /usr/local/lib/node_modules/pa11y/bin/pa11y.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/pa11y/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
Chromium downloaded to /usr/local/lib/node_modules/pa11y/node_modules/puppeteer/.local-chromium/linux-686378
+ pa11y@5.3.0
added 71 packages from 58 contributors in 31.72s
```

**Comment by josebolos** [comment] 2021-02-08 18:08
Thanks for creating this issue. It looks like this may be fixed now, feel free to reopen the issue if not.

**Closed by josebolos** 2021-02-08 18:08 UTC

**Comment by smustgrave** [comment] 2021-02-20 18:39
How did you guys fix this? I'm still getting this error on my mac?

**Comment by josebolos** [comment] 2021-02-21 00:13
Hi @smustgrave, as this issue is now closed, could you please create a new issue with the exact error message you're getting and the steps to reproduce it? Thanks!
