### ISSUE TITLE
Using actions to login to sites is not working

### ISSUE THREAD

**Issue by amwhalen** [pa11y/pa11y#421] opened 2018-08-16 20:24 UTC
## Expected behaviour

Using actions to login to a site before performing analysis should work correctly.

## Actual behaviour

I've been unable to login to any site, as none of the actions after clicking on a submit button are reached.

As a test to see where the problem lies, I did create a puppeteer-only version of the actions. The puppeteer version filled out the login form and submitted the form - and it worked great. I'm thinking there's something happening between the pa11y library and puppeteer which could be causing something to hang around and cause further steps from completing.

I also posted this issue on StackOverflow, but I'm posting here too since one person did respond on StackOverflow that they had the same exact issue (the mods have since removed that person's reply since it wasn't an answer). https://stackoverflow.com/questions/51868635/unable-to-use-pa11y-actions-to-login-to-sites

## Steps to reproduce

Running the following code hangs after the `click` action and eventually times out (enter your own valid GitHub credentials before running).

```
'use strict';

const pa11y = require('pa11y');

runExample();

async function runExample() {

  try {

    var urlToTest = 'https://github.com/login';

    const result = await pa11y(urlToTest, {

      actions: [
        'navigate to https://github.com/login',
        'set field #login_field to MYUSERNAME',
        'set field #password to MYPASSWORD',
        'click element #login input.btn.btn-primary.btn-block',
        // everything stops here...
        'wait for url to not be https://github.com/login',
        'navigate to https://github.com/settings/profile',
        'screen-capture github.png'
      ],

      chromeLaunchConfig: {
        headless: false,
        slowMo: 250
      },

      log: {
        debug: console.log,
        error: console.error,
        info: console.log
      },

      timeout: 90000

    });

    console.log(result);

  } catch (error) {
    console.error(error.message);
  }

}
```

## Environment:
```
Pa11y:      5.0.4
Node.js:    8.11.3
npm:        5.6.0
OS:         17.6.0 (darwin)
```

**Comment by hollsk** [comment] 2018-08-28 14:38
Hi @amwhalen - thanks for the detailed issue. I've just tried your test case and everything works fine for me, so I wonder if it's system-specific? I'll run another test on a different setup shortly to see if it makes a difference, but I can't replicate on this one. 

For any other users reading who are having the same problem, could you please run `pa11y -n` and paste the output into this issue? Maybe there's a pattern that'll become apparent.

For comparison, my (working) setup uses:

```
Pa11y:      5.0.4
Node.js:    8.11.1
npm:        5.6.0
OS:         15.5.0 (darwin)
```

**Comment by robertshilston** [comment] 2018-08-28 14:38
In a clean environment, I've not been able to reproduce hanging or timeouts, which I believe is the core issue reported.  My environment is:

Pa11y:      5.0.4
Node.js:    8.11.4 (you were on 8.11.3)
npm:        5.6.0
OS:         17.7.0 (you were on 17.6.0)

In other projects, I've found Chromium versions can cause issues.  In my environment, I've got puppeteer v1.7.0, which pullet in Chromium 70.0.3508.0.

**Comment by wjamro** [comment] 2018-08-29 14:03
The problem also occurs on my side.

**pa11y -n** output:
```bash
Pa11y:      5.0.4
Node.js:    8.10.0
npm:        5.6.0
OS:         16.7.0 (darwin)
```

Problem dispears after turning off `setRequestInterception` (https://github.com/pa11y/pa11y/blob/master/lib/pa11y.js#L119)
```javascript
await page.setRequestInterception(false);
```

If you check `puppeteer` repo you can spot increasing number of issues touching problem with `setRequestInterception` in the last couple weeks. (https://github.com/GoogleChrome/puppeteer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+setRequestInterception)

W can:
- wait for new version of puppeteer
- add toggle which will turn off `setRequestInterception` if you are not using custom method, userAgent or postData - most of users should benefit from this mechanism till puppeteer fix

**Comment by amwhalen** [comment] 2018-08-29 15:05
Thank you for the responses so far. It gives me hope that others are able to successfully use this.

Thanks @wjamro for the lead on `setRequestInterception`! I set it to `false` and indeed the script completed as expected. It did throw a bunch of errors/warnings, but nothing that seemed to stop the process:

```
(node:22793) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:22793) UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!
    at assert (/Users/awhalen/Sites/eprojects/node_modules/puppeteer/lib/helper.js:283:11)
    at Request.continue (/Users/awhalen/Sites/eprojects/node_modules/puppeteer/lib/NetworkManager.js:412:5)
    at Page.page.on.interceptedRequest (/Users/awhalen/Sites/eprojects/node_modules/pa11y/lib/pa11y.js:151:30)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at NetworkManager.Page._networkManager.on.event (/Users/awhalen/Sites/eprojects/node_modules/puppeteer/lib/Page.js:125:74)
    at emitOne (events.js:116:13)
    at NetworkManager.emit (events.js:211:7)
    at NetworkManager._handleRequestStart (/Users/awhalen/Sites/eprojects/node_modules/puppeteer/lib/NetworkManager.js:247:10)
    at NetworkManager._onRequest (/Users/awhalen/Sites/eprojects/node_modules/puppeteer/lib/NetworkManager.js:200:10)
```

I did try this on another two environments. I saw the same behavior on all of them - stopping at the POST request for login. One environment was a mac that's similar to the first mac I tried on. The other environment was inside a node:8 docker container on a remote machine (trying to cross off my own network as the culprit).

Mac 1:
```
Pa11y:      5.0.4
Node.js:    8.11.4
npm:        5.6.0
OS:         17.7.0 (darwin)
```

Mac 2:
```
Pa11y:      5.0.4
Node.js:    8.11.3
npm:        6.4.0
OS:         17.7.0 (darwin)
```

Docker / standard node:8 container (https://github.com/nodejs/docker-node/blob/72dd945d29dee5afa73956ebc971bf3a472442f7/8/jessie/Dockerfile):
```
Pa11y:      5.0.4
Node.js:    8.11.4
npm:        5.6.0
OS:         4.4.0-116-generic (linux)
```

It was a little bit of a process to get the docker container setup, but I basically followed the suggestions at https://github.com/Googlechrome/puppeteer/issues/290#issuecomment-322921352, and used the arg of `--no-sandbox` for chromium to get it running in docker: 

```
chromeLaunchConfig: {
  headless: true,
  args: ['--no-sandbox']
},
```

**Comment by hollsk** [comment] 2018-08-29 16:48
The puppeteer thing _is_ interesting, thanks @wjamro. My working env is running Puppeteer v1.4.0 - (specified in Pa11y's package.json). But then again @robertshilston is on v1.7.0 and it's working fine for him 🤔 

@amwhalen does anything interesting happen if you specify Puppeteer 1.6.2, per the second comment here https://github.com/GoogleChrome/puppeteer/issues/3118 ?

**Comment by amwhalen** [comment] 2018-08-29 20:45
I can confirm that when pa11y is used with puppeteer 1.6.2, things are working as they should! No timeouts or hanging.

**Comment by amwhalen** [comment] 2018-08-29 20:46
Also make note that I was previously using puppeteer 1.7.0 when I was having the timeout issues.

**Comment by amwhalen** [comment] 2018-10-01 16:19
The pull request in #426 appears to fix this issue. The workaround to use puppeteer 1.6.2 is no longer working for me.

**Comment by hollsk** [comment] 2018-10-18 12:28
The workaround by @edoardocavazza was released in [5.10](https://github.com/pa11y/pa11y/releases/tag/5.1.0) - thanks to everyone for helping figure this one out 😄

**Closed by hollsk** 2018-10-18 12:28 UTC
Labels: priority: high, type: bug

**Comment by corchard** [comment] 2021-03-03 00:21
@hollsk  5.1.0 Appears to work fine, but I was initially using 5.3.0 and ran into this issue before having to downgrade.  Looks like it broke again?

**Comment by josebolos** [comment] 2021-03-03 10:36
Hi @corchard,

As this issue is closed, could you please create a new issue detailing the problem that your finding, and the exact steps to reproduce it?

Thanks!
