### ISSUE TITLE
Call JavaScript function using Actions

### ISSUE THREAD

**Issue by twinfred** [pa11y/pa11y#435] opened 2018-10-22 20:40 UTC
The "Click element..." action doesn't trigger the #JavaScript "onclick" function that's attached to the button that's being clicked (see code snippet below). Would love a Pa11y action that allows me to call a JavaScript function directly.

```
'use strict';

const pa11y = require('pa11y');

function runPally() {
    pa11y('https://tickets.fandango.com/transaction/ticketing/express/ticketboxoffice.aspx?row_count=246950456&tid=AAAAQ&mid=209222&rfilter=row_count,sdate&from=Redirect.aspx&sdate=2018-10-18%2022:15&refreshdate=', {
        standard: 'WCAG2AA',
        actions: [
            'wait for element #AreaRepeater_TicketRepeater_0_quantitytb_0 to be visible',
            'set field #AreaRepeater_TicketRepeater_0_quantitytb_0 to 1',
            'click element #NewCustomerCheckoutButton', // why does clicking the button not load a new page?
            'wait for element #orderSummary to be visible', // never becomes visible because #NewCustomerCheckoutButton's function isn't being called
            'screen capture checkout.jpg',
        ],
        log: {
            debug: console.log,
            error: console.error,
            info: console.log
        },
        wait: 3000

    .then((results) => {
        console.log(results);
    });
}

runPally();
```

**Comment by GlynnPhillips** [comment] 2018-10-22 21:12
Hi @twinfred, Unfortunately I am unable to reproduce the the issue you describe. I don't know any details about the site you are testing in the example above but looking at the page that gets rendered for me it looks like it might be testing the wrong page.

Loading this page `https://tickets.fandango.com/transaction/ticketing/express/ticketboxoffice.aspx?row_count=246950456&tid=AAAAQ&mid=209222&rfilter=row_count,sdate&from=Redirect.aspx&sdate=2018-10-18%2022:15&refreshdate=` I am unable to find the elements you have referenced in your actions.

I would suggest checking the pages you are testing and make sure theres not any factors that might cause you to see a different page to the Pa11y tests.

Here I have tweaked your example to show the click action working with an onclick handler.

```
'use strict';

const pa11y = require('pa11y');

function runPally() {
    pa11y('https://output.jsbin.com/samuwojuyi', {
        standard: 'WCAG2AA',
        actions: [
            'wait for element #click to be visible',
            'click element #click',  
            'wait for element #soon-to-be-hidden to be hidden',
            'screen capture output.jpg', // You will see the #soon-to-be-hidden isn't visible 
        ],
        log: {
            debug: console.log,
            error: console.error,
            info: console.log
        },
        wait: 3000
    })
    .then((results) => {
        console.log(results);
    })
}
runPally();

```

**Comment by twinfred** [comment] 2018-10-22 21:17
@GlynnPhillips Apologies. I edited the code snippet above to use the correct URL.

**Comment by GlynnPhillips** [comment] 2018-10-22 21:30
@twinfred I am afraid I am still unable to find the elements you are referencing in the actions. Here is an example of the page that is loading for me and showing that the `#AreaRepeater_TicketRepeater_0_quantitytb_0` doesn't exist.

When I run your example script it stops at the first action, where it waits for that element to exist.

![Gif showing the loaded web page and using the console to find the existence of an element](https://user-images.githubusercontent.com/524573/47320648-f1a6d780-d649-11e8-8e03-d65b146e4ee4.gif)

**Comment by twinfred** [comment] 2018-10-23 23:11
Sorry, something was wrong with that link. If you swap out the link with this one it should work:
https://tickets.fandango.com/transaction/ticketing/express/ticketboxoffice.aspx?row_count=246095285&tid=AAWDZ&sdate=2018-10-31+22:15&mid=209222&from=mov_det_showtimes

**Comment by josebolos** [comment] 2021-02-08 18:15
Thanks for creating this issue. It looks like this may be fixed now, feel free to reopen the issue if not.

**Closed by josebolos** 2021-02-08 18:15 UTC
