### ISSUE TITLE
beforeScript - page

### ISSUE THREAD

**Issue by ezraroda** [pa11y/pa11y#197] opened 2016-11-09 18:53 UTC
Sorry for the newbies question, 
I'm trying to perform login using the beforeScript option, I tried both CLI and JS, but I keep getting "page" as empty object {} parameter to beforeScript function.

```
beforeScript: function(page, options, next) {
// page is alway empty object....
		options.log.debug('Running beforeScript inner' + JSON.stringify(page));
...
}
```

I'm using:
phantomjs - v2.1.1
node - v6.9.1

Installed pa11y using : npm install pa11y
which include already "node-phantom-simple" bridge

Looks like I'm missing something basic, 
Any other dependencies are required ?

**Comment by ezraroda** [comment] 2016-11-10 00:49
The HeadlessError is thrown from node-phantom-simple.js line 258
`callback(new HeadlessError('Error executing command to extract phantom ports: ' + err));`
after failing to run the mac command to find the port phantomjs is listening:
```
case 'darwin':
          cmd = 'lsof -np %d | grep LISTEN';
          break;
```

Any idea ?

**Comment by rowanmanning** [comment] 2016-11-10 10:53
Hey @ezraroda. I think `JSON.stringify(page)` will always return `{}` because it doesn't have any properties that can be JSON stringified – I think they're all functions.

Have you tried running something simple with the `beforeScript`, like the stuff in the examples?

**Comment by ezraroda** [comment] 2016-11-10 14:01
Hey Rowen,
Thanks for your reply!
Yes, I did try something simple like printing out document.title, but it never goes into page.evaluate function when called inside beforeScript.

Seems like the error is thrown from node-phantom-simple when trying to look for the listening phantoms port in Mac.

Any idea?


- Ezra

**Comment by ezraroda** [comment] 2016-11-10 18:52
Running the following :

```
'use strict';

var pa11y = require('pa11y');

var beforeScriptTester = pa11y({
    allowedStandards: ['WCAG2AA'],
    log: {
        debug: console.log.bind(console),
        error: console.error.bind(console),
        info: console.log.bind(console)
    },
    beforeScript: function (page, options, next) {

        options.log.debug(' >>> beforeScript called ');

        var callBack = function () {
            options.log.debug(' >>> callBack called ');
            next();
        };

        // ========= this one is never called :(
        page.evaluate(function (innerOptions) {

            console.log(JSON.stringify(innerOptions));        
            innerOptions.log.debug(' >>> page.evaluate called ' + document.title);
        }, options, callBack);
    }
});

beforeScriptTester.run('http://www.apple.com', function (error, result) {
    if (error) {
        return console.error(error.message);
    }
    console.log('All done !');
});
```

Print output:

```
$> node index-test.js 
PhantomJS browser created
PhantomJS page created
Opening "http://www.apple.com" in PhantomJS
Opened "http://www.apple.com" in PhantomJS
Testing the page "http://www.apple.com"
Running beforeScript
 >>> beforeScript called 
 >>> callBack called 
Injecting HTML CodeSniffer
Injecting Pa11y
Running Pa11y on the page
Test function ran for "http://www.apple.com"
PhantomJS page closed
PhantomJS browser exited
All done !
```

```
node -v -> v6.9.1
phantomjs -v -> 2.1.1
```



Anything wrong with `page.evaluate` ??

**Comment by rowanmanning** [comment] 2016-11-11 09:58
Ah yes, the issue is that your `page.evaluate` call is in a _PhantomJS_ context, not a Node.js one. It can't have direct access to functions defined in Node.js because the function is run in a completely different environment. It's confusing, I know, but a limitation of the way we communicate with PhantomJS.

If you're trying to get the title of the page, I've modified your example to work. The way you send data from PhantomJS back to Node.js is by returning – the returned value will be available in the callback:

```js
'use strict';

var pa11y = require('pa11y');

var beforeScriptTester = pa11y({
    allowedStandards: ['WCAG2AA'],
    log: {
        debug: console.log.bind(console),
        error: console.error.bind(console),
        info: console.log.bind(console)
    },
    beforeScript: function (page, options, next) {

        options.log.debug(' >>> beforeScript called ');

        var callBack = function (error, result) {
            options.log.debug(' >>> page.evaluate result ' + result);
            options.log.debug(' >>> callBack called ');
            next();
        };

        page.evaluate(function (innerOptions) {
            return document.title;
        }, options, callBack);
    }
});

beforeScriptTester.run('http://www.apple.com', function (error, result) {
    if (error) {
        return console.error(error.message);
    }
    console.log('All done !');
});
```

I hope this helps. Closing now, but we can reopen if you have further issues :)

**Closed by rowanmanning** 2016-11-11 09:58 UTC
