### ISSUE TITLE
Err_Cert_Authority inspite of ignore SSL warnings

### ISSUE THREAD

**Issue by naveen7036** [pa11y/pa11y#440] opened 2019-01-02 14:31 UTC
Tried running the qa environment urls as well as uat env, still getting the same issues, inspite of using the ignore ssl warnings and downloading and importing the certificates. Able to launch the pages manually on browser.

C:\Users\nbysai\node_modules\pa11y>pa11y --ignore-ssl-errors=true http://<test-global.sc.testsasdfasdfsafd.com/>

Welcome to Pa11y

 > Running Pa11y on URL http://<test-global.sc.testsasdfasdfsafd.com/>
ERROR: The process with PID 10940 (child process of PID 10420) could not be term
inated.
Reason: There is no running instance of the task.

Error: net::ERR_CERT_AUTHORITY_INVALID at http://uat-global.sc.allianzgi-intra.c
om/
    at navigate (C:\Users\nbysai\AppData\Roaming\npm\node_modules\pa11y\node_mod
ules\puppeteer\lib\FrameManager.js:103:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\nbysai\AppData\Roaming\npm\node_modules\pa11y
\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.goto (C:\Users\nbysai\AppData\Roaming\npm\node_modules\pa11y\node_mo
dules\puppeteer\lib\Page.js:579:49)
    at Page.<anonymous> (C:\Users\nbysai\AppData\Roaming\npm\node_modules\pa11y\
node_modules\puppeteer\lib\helper.js:145:23)
    at runPa11yTest (C:\Users\nbysai\AppData\Roaming\npm\node_modules\pa11y\lib\
pa11y.js:166:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

C:\Users\nbysai\node_modules\pa11y>

For a bug report, please use the template below:

---

## Environment:
```
(please run `pa11y --environment` and paste the output here)
Pa11y:      5.0.4
Node.js:    8.12.0
npm:        6.4.1
OS:         6.1.7601 (win32)
```

**Comment by josebolos** [comment] 2019-05-16 10:19
Marking as duplicate of #439.

**Closed by josebolos** 2019-05-16 10:19 UTC
